### ISSUE TITLE
Sandbox mode

### ISSUE THREAD

**Issue by diidiiman** [coinbase/omniauth-coinbase#14]
Sandbox mode flag in initialiser is working code-wise since it directs to sandbox.coinbase.com, but the domain name is not resolving. Is there something that should be adjusted on my end, or is that a genuine issue?

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :coinbase,
    ENV["COINBASE_CLIENT_ID"],
    ENV["COINBASE_CLIENT_SECRET"],
    scope: 'wallet:user:read wallet:user:email wallet:accounts:read',
    sandbox: (Rails.env.production? ? false : true)
end
```

**Comment by diidiiman** [comment]
This probably goes hand in hand with this issue:
When supplying a return url in the Coinbase dashboard it is not showing any errors, although when I try with my local environment with the same url, Coinbase is bringing up the error: "The redirect uri included is not valid."

**Comment by icco** [comment]
coinbase ruby removed sandbox from docs, so I'm guessing it is no longer supported. https://github.com/coinbase/coinbase-ruby/commit/51780c7b7e65adc805e061926b1138db83b7bcb1
