### ISSUE TITLE
Applying additional oauth scopes in the initializer

### ISSUE THREAD

**Issue by d00medman** [coinbase/omniauth-coinbase#15]
I am trying to apply the coinbase wallet API with oauth to use its send functionality via this gem. I have been able to connect to the API and use its endpoints, but whenever I try to use the send functionality, I am thrown the error `Invalid amount for meta[send_limit_amount]`. My omniauth initializer looks like this:

```ruby
provider :coinbase, , ENV['CLIENT_ID'], ENV['CLIENT_SECRET'], 
scope: 'wallet:user:read wallet:user:email wallet:accounts:read wallet:transactions:send'
```

The reason for this error is because, in order to use the send functionality, coinbase requires additional parameter meta[send_limit_amount]. Where and how am I supposed to apply this additional scope? There really doesn't seem to be any good documentation for how I can go about doing this, so I figured I'd go straight to the source. Any help would be tremendously appreciate!

**Comment by tgoldenberg** [comment]
Getting the same error here. @d00medman, were you able to find a solution?

**Comment by tgoldenberg** [comment]
<img width="360" alt="screenshot 2017-11-22 17 11 46" src="https://user-images.githubusercontent.com/10930134/33151980-507cbfa8-cfa8-11e7-9e6d-980b2a8c3974.png">

@mihar @barmstrong @EthanHeilman @grahamjenson  Any thoughts on this?

**Comment by go0sedev** [comment]
Please look at the following link:
https://developers.coinbase.com/docs/wallet/coinbase-connect/permissions

"To better protect Coinbase users, the wallet:transactions:send permission requires additional OAuth authorize parameters and two factor authentication. Here is a list of additional parameters:"

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
