### ISSUE TITLE
Getting Token

### ISSUE THREAD

**Issue by chadstachowicz** [coinbase/omniauth-coinbase#17]
From what I can see this library is useless.  You get back an authorization code, but when you use that in another client / http request you always get back..
"error"=>"invalid_grant", "error_description"=>"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."

Also coinbase-ruby doesn't support getting a token either.... so I can get this working by using HTTParty all the way through an manually building my own OAUTH, whats the point of this library if you can't use it to get a token?

**Comment by OMarciano** [comment]
+1

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
