### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by acoravos** [coinbase/omniauth-coinbase#9]
Link to "list of OAuth Permissions" doesn't work in the README.md file.

**Comment by pkpp1233** [comment]
+1.

Seems like scopes in this repo don't match what's in docs. How to simply access data API?

**Comment by jorilallo** [comment]
This strategy is still using v1 of our API and you can find the list here: https://developers.coinbase.com/api/v1#permissions-scopes

I'll update this soon for v2.
